name: cron-send-email
on:
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: "0 14 * * SUN"

jobs:
  cron-send-email:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v1

      - name: Pull data and send email
        run: |
          Rscript main.R \
            --search_area_latitude ${{ secrets.SEARCH_AREA_LATITUDE }} \
            --search_area_longitude ${{ secrets.SEARCH_AREA_LONGITUDE }} \
            --from_address ${{ secrets.FROM_ADDRESS }} \
            --to_addresses ${{ secrets.TO_ADDRESSES }} \
            --smtp_user ${{ secrets.SMTP_USER }} \
            --smtp_password ${{ secrets.SMTP_PASSWORD }}
