name: cron-send-email
on:
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: "0 14 * * SUN"

jobs:
  cron-send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up virtual environment
        run: make venv

      - name: Pull data and send email
        run: |
          . ./venv/bin/activate
          main \
            --search-area-latitude ${{ secrets.SEARCH_AREA_LATITUDE }} \
            --search-area-longitude ${{ secrets.SEARCH_AREA_LONGITUDE }} \
            --from-address ${{ secrets.FROM_ADDRESS }} \
            --to-addresses ${{ secrets.TO_ADDRESSES }} \
            --smtp-user ${{ secrets.SMTP_USER }} \
            --smtp-password ${{ secrets.SMTP_PASSWORD }}
